[tool.black]
line-length = 99
skip-string-normalization = true
target-version = ['py37']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.env
    | _build
    | buck-out
    | build
    | dist
  )/

  | smart_attendance/settings.py  # ignore local settings
  | /migrations/                      # ignore migrations
  | /site-packages/                   # ignore thrid-party packages
)
'''
